defaults = { "STATE_IDLE", "IMPULSE_NO" , "BROADCAST_NO"}

boundary = {}
boundary[0] = { ["X0000Y0000"] = {"STATE_INIT","IMPULSE_YES"} }

ending = {}

styles = { registers_default = { color = "black" } , BROADCAST_SENT = { arrowhead = "normal", arrowtail = "normal", color = "black" }, messages_default =  { arrowhead = "none", arrowtail = "none", color = "grey80" } }

report = { "TIME_COMPLEXITY", "MESSAGE_COMPLEXITY" }
